//go:build !require
// +build !require

// Code generated by chaingen. DO NOT EDIT.

package logt

func (r Require) NotEmpty(msgAndArgs ...any) {
	r.assert.filter.T.t.Helper()
	r.require(r.assert.NotEmpty(msgAndArgs...))
}

func (r Require) Empty(msgAndArgs ...any) {
	r.assert.filter.T.t.Helper()
	r.require(r.assert.Empty(msgAndArgs...))
}

func (r Require) Count(count int, msgAndArgs ...any) {
	r.assert.filter.T.t.Helper()
	r.require(r.assert.Count(count, msgAndArgs...))
}

func (r Require) Message(expected string, msgAndArgs ...any) {
	r.assert.filter.T.t.Helper()
	r.require(r.assert.Message(expected, msgAndArgs...))
}

func (r Require) Attr(name string, expected any, msgAndArgs ...any) {
	r.assert.filter.T.t.Helper()
	r.require(r.assert.Attr(name, expected, msgAndArgs...))
}

func (r RequireGroup[K]) Count(expected map[K]int, msgAndArgs ...any) {
	r.assert.group.T.t.Helper()
	r.require(r.assert.Count(expected, msgAndArgs...))
}
