//go:build !lgq
// +build !lgq

// Code generated by chaingen. DO NOT EDIT.

package logq

import (
	"github.com/AnatolyRugalev/observ/internal/genq"
)

func (f Filter) Where(operands ...genq.FilterFunc[Record]) Filter {
	return f.wrap(f.filter.Where(operands...))
}

func (f Filter) And(operands ...genq.FilterFunc[Record]) Filter {
	return f.wrap(f.filter.And(operands...))
}

func (f Filter) Or(operands ...genq.FilterFunc[Record]) Filter {
	return f.wrap(f.filter.Or(operands...))
}
